export const errorMessages = {
  chargeFailed: 'We were unable to charge your account. Please change the payment method or try again later.',
  passwordContent: 'Password must contain a number, special character, lowercase and uppercase character.',
  privacyPolicyRequired: 'Before signing up, you need to agree to the Privacy and Policy.',
  actionPerform: 'There was an error performing this action. Please try again later.',
  termsRequired: 'Before signing up, you need to agree to the terms of use.',
  contactRecover: 'There was a problem while recovering contact(s).',
  duplicateParent: 'Node with this name already exists in parents',
  duplicateChild: 'Node with this name already exists in children',
  markAsRead: "The conversation could not be marked as 'Read'.",
  nameCharsMaxLength: 'Name must contain maximum 50 characters',
  cannotDelete: 'There was a problem while deleting items(s).',
  campaignNameLength: 'Please type a minimum of 5 characters.',
  conditionNoMatch: 'There is no match with any conditions.',
  datePicker: 'The close date must be after the open date.',
  charsMinLength: 'Please type a minimum of 2 characters.',
  passwordLength: 'Please type a minimum of 8 characters.',
  disableAutoResponse: 'Could not disable auto-responses.',
  ownParentChild: 'Node cannot be its own parent or child',
  passwordsIdentical: 'Please enter identical passwords.',
  couldNotGetAutoResponse: 'Could not get auto-responses',
  charsMaxLength: 'Please type of maximum 30 characters',
  enableAutoResponse: 'Could not enable auto-responses.',
  planSelect: 'Please select a plan before moving on.',
  phoneIncorrect: 'Please type a valid phone number.',
  couldNotChangeStatus: 'Could not change the status',
  sampleDownload: 'Unable to download the sample',
  updateFailed: 'The update was not performed.',
  unauthorized: 'Authorization key is missing.',
  invalidContact: 'There are no valid contacts',
  companySelect: 'Please select your company.',
  zip: 'Please consider typing only numbers.',
  email: 'Please type a valid email address.',
  invalidCredentials: 'Invalid credentials.',
  invalidContextName: 'Invalid context name',
  messageEdit: 'Unable to edit the message',
  invalidNumber: 'The number is invalid.',
  nameUnique: 'The name must be unique.',
  expiredLink: 'The link was expired.',
  itemsNotFound: 'Item(s) not found.',
  verifyFailed: 'Verification failed',
  invalidDate: 'The date is invalid.',
  wentWrong: 'Something went wrong.',
  importFailed: 'Importing failed',
  exportFailed: 'Export failed',
  missingToken: 'Invalid Token',
  invalidToken: 'Invalid Token',
  missingUser: 'Missing user',
  required: 'Required',
};
